import { IResumeData } from '@/types/IResumeData';

export const initialFrenchResumeData: IResumeData = {
  contactInformation: {
    fullName: 'John Smith, ing.',
    jobTitle: 'Ingénieur civil & Gestionnaire de projets',
    emailAddress: 'john.smith@example.com',
    phoneNumber: '(514) 555-0146',
    locationAddress: 'Montréal, QC',
    websiteUrl: 'https://johnsmith.dev',
    linkedinUrl: 'linkedin.com/in/john-smith',
    githubUrl: '',
  },
  profileSummary:
    'Ingénieur civil professionnel et gestionnaire de projets avec plus de 5 ans d\'expérience dans la planification d\'infrastructures, la modélisation technique et la direction d\'équipes multidisciplinaires. Reconnu pour optimiser les budgets, respecter les échéanciers serrés et garantir les plus hauts standards de qualité.',
  skillsList: [
    'Gestion de projets & coordination de chantier',
    'AutoCAD, Revit & modélisation 3D',
    'Estimation des coûts & gestion budgétaire',
    'Analyse structurelle (ETABS, SAFE, SAP2000)',
    'Contrôle qualité & conformité réglementaire',
    'Négociation contractuelle & appels d\'offres',
  ],
  languagesList: [
    'Français (langue maternelle)',
    'Anglais (courant / professionnel)',
    'Espagnol (intermédiaire)',
  ],
  certificationsList: [
    {
      identifier: 'cert-1',
      certificationName: 'Professionnel en gestion de projet (PMP)®',
      issuingOrganization: 'Project Management Institute (PMI)',
      issueYear: '2023',
      iconName: 'id-card',
    },
    {
      identifier: 'cert-2',
      certificationName: 'Santé et sécurité générale sur les chantiers de construction',
      issuingOrganization: 'ASP Construction',
      issueYear: '2021',
      iconName: 'shield',
    },
    {
      identifier: 'cert-3',
      certificationName: 'Certificat de secourisme en milieu de travail et RCR',
      issuingOrganization: 'Croix-Rouge',
      issueYear: '2022',
      iconName: 'plus-square',
    },
  ],
  educationList: [
    {
      identifier: 'edu-1',
      degreeName: 'Baccalauréat en génie civil (B.Ing.)',
      institutionName: 'Université d\'Ingénierie & Technologie',
      locationName: 'Montréal, QC',
      startDate: '2017',
      endDate: '2021',
      specialization: 'Infrastructures & Structures Durables',
      bulletPoints: ['Mention d\'excellence académique – Projet de fin d\'études primé'],
    },
    {
      identifier: 'edu-2',
      degreeName: 'Diplôme d\'études collégiales (DEC) en Sciences Pures',
      institutionName: 'Collège d\'Études Supérieures',
      locationName: 'Montréal, QC',
      startDate: '2015',
      endDate: '2017',
      specialization: 'Sciences Pures et Appliquées',
      bulletPoints: [],
    },
  ],
  projectsList: [
    {
      identifier: 'proj-1',
      projectTitle: 'Projet d\'optimisation des infrastructures urbaines',
      projectSubtitle: 'Programme d\'ingénierie durable, QC',
      startDate: 'Sept. 2020',
      endDate: 'Avr. 2021',
      bulletPoints: [
        'Direction d\'une équipe de sept ingénieurs pour concevoir un complexe multifonctionnel durable intégrant des systèmes parasismiques avancés.',
        'Modélisation complète sous ETABS et réalisation des analyses de charge statiques et dynamiques.',
      ],
    },
    {
      identifier: 'proj-2',
      projectTitle: 'Compétition nationale de conception technique',
      projectSubtitle: 'Société Canadienne de Génie Civil',
      startDate: 'Fév. 2020',
      endDate: 'Fév. 2020',
      bulletPoints: [
        'Conception et fabrication d\'un prototype structurel à haute efficacité ayant obtenu le 1er prix d\'optimisation du ratio résistance/poids.',
        'Rédaction du rapport technique et présentation devant un panel d\'experts industriels.',
      ],
    },
  ],
  experienceList: [
    {
      identifier: 'exp-1',
      jobTitle: 'Chargé de projets principal – Infrastructures',
      companyName: 'Acme Global Technologies',
      locationName: 'Montréal, QC',
      startDate: 'Août 2022',
      endDate: 'Présent',
      isCurrentRole: true,
      bulletPoints: [
        'Superviser simultanément de multiples projets d\'infrastructure majeurs avec des enveloppes budgétaires supérieures à 15M$.',
        'Coordonner les équipes d\'ingénieurs, architectes et sous-traitants pour assurer une livraison rigoureuse dans les délais.',
        'Préparer les devis techniques, gérer les appels d\'offres et négocier les ententes contractuelles avec les partenaires.',
        'Mettre en place des protocoles stricts de contrôle de qualité et d\'assurance environnementale sur l\'ensemble des chantiers.',
      ],
    },
    {
      identifier: 'exp-2',
      jobTitle: 'Ingénieur de projets & Estimation des coûts',
      companyName: 'Apex Solutions Inc.',
      locationName: 'Montréal, QC',
      startDate: 'Mai 2021',
      endDate: 'Août 2022',
      isCurrentRole: false,
      bulletPoints: [
        'Élaborer des modèles prévisionnels d\'estimation des coûts pour des projets d\'envergure commerciale et résidentielle.',
        'Analyser les plans d\'ingénierie et effectuer les relevés quantitatifs détaillés à l\'aide d\'outils numériques spécialisés.',
        'Optimiser la gestion de la chaîne d\'approvisionnement, générant une réduction des coûts directs de 12%.',
      ],
    },
    {
      identifier: 'exp-3',
      jobTitle: 'Stagiaire en ingénierie de structures',
      companyName: 'Horizon Capital Group',
      locationName: 'Montréal, QC',
      startDate: 'Janv. 2020',
      endDate: 'Avr. 2021',
      isCurrentRole: false,
      bulletPoints: [
        'Participer à la revue des dessins d\'atelier et à la validation de la conformité aux codes du bâtiment en vigueur.',
        'Rédiger les rapports d\'inspection périodiques et documenter l\'état d\'avancement pour les clients et partenaires.',
      ],
    },
  ],
  customSectionsList: [],
  sectionOrder: [
    'profile',
    'education',
    'projects',
    'experience',
    'skills',
    'languages',
    'certifications',
  ],
  sectionVisibility: {
    profile: true,
    education: true,
    projects: true,
    experience: true,
    skills: true,
    languages: true,
    certifications: true,
  },
};

export const initialEnglishResumeData: IResumeData = {
  contactInformation: {
    fullName: 'John Smith, P.Eng.',
    jobTitle: 'Senior Project Engineer',
    emailAddress: 'john.smith@example.com',
    phoneNumber: '(514) 555-0146',
    locationAddress: 'Montreal, QC, Canada',
    websiteUrl: 'https://johnsmith.dev',
    linkedinUrl: 'linkedin.com/in/john-smith',
    githubUrl: '',
  },
  profileSummary:
    'Senior Project Engineer and Technical Manager with 5+ years of experience leading cross-functional engineering teams, overseeing infrastructure initiatives, and delivering complex capital projects on time and within budget. Proven expertise in quality assurance, cost optimization, and stakeholder management.',
  skillsList: [
    'Project Lifecycle Management & Agile Delivery',
    'AutoCAD, Revit & BIM Modeling',
    'Cost Estimation & Budget Governance',
    'Structural & Systems Analysis (ETABS, SAP2000)',
    'Quality Assurance & Regulatory Compliance',
    'Contract Negotiation & Vendor Procurement',
  ],
  languagesList: [
    'English (Native / Fluent)',
    'French (Professional Working Proficiency)',
    'Spanish (Conversational)',
  ],
  certificationsList: [
    {
      identifier: 'cert-en-1',
      certificationName: 'Project Management Professional (PMP)®',
      issuingOrganization: 'Project Management Institute (PMI)',
      issueYear: '2023',
      iconName: 'id-card',
    },
    {
      identifier: 'cert-en-2',
      certificationName: 'Occupational Health & Safety (OHS) Certification',
      issuingOrganization: 'Safety Standards Council',
      issueYear: '2021',
      iconName: 'shield',
    },
    {
      identifier: 'cert-en-3',
      certificationName: 'Workplace First Aid & CPR Level C',
      issuingOrganization: 'Red Cross',
      issueYear: '2022',
      iconName: 'plus-square',
    },
  ],
  educationList: [
    {
      identifier: 'edu-en-1',
      degreeName: 'Bachelor of Science in Engineering (B.Sc. Eng.)',
      institutionName: 'State University of Technology',
      locationName: 'Montreal, QC',
      startDate: '2017',
      endDate: '2021',
      specialization: 'Civil & Structural Engineering',
      bulletPoints: ['Graduated with Academic Honors – Outstanding Capstone Design Award'],
    },
    {
      identifier: 'edu-en-2',
      degreeName: 'Associate Degree in Pure & Applied Sciences',
      institutionName: 'College of Higher Education',
      locationName: 'Montreal, QC',
      startDate: '2015',
      endDate: '2017',
      specialization: 'Applied Mathematics & Physics',
      bulletPoints: [],
    },
  ],
  projectsList: [
    {
      identifier: 'proj-en-1',
      projectTitle: 'Sustainable Urban Infrastructure Program',
      projectSubtitle: 'Engineering Excellence Initiative, QC',
      startDate: 'Sep. 2020',
      endDate: 'Apr. 2021',
      bulletPoints: [
        'Directed a 7-member multidisciplinary engineering team to design a sustainable multi-purpose facility with seismic-resilient framing.',
        'Constructed complete 3D structural simulation models in ETABS and performed rigorous static and dynamic load verifications.',
      ],
    },
    {
      identifier: 'proj-en-2',
      projectTitle: 'National Technical Design & Bridge Competition',
      projectSubtitle: 'Canadian Society for Civil Engineering',
      startDate: 'Feb. 2020',
      endDate: 'Feb. 2020',
      bulletPoints: [
        'Designed and constructed an optimized prototype structure that secured 1st place for structural efficiency and strength-to-weight ratio.',
        'Authored the comprehensive engineering report and presented findings to an executive industry review panel.',
      ],
    },
  ],
  experienceList: [
    {
      identifier: 'exp-en-1',
      jobTitle: 'Senior Project Lead – Infrastructure & Capital Works',
      companyName: 'Acme Global Technologies',
      locationName: 'Montreal, QC',
      startDate: 'Aug. 2022',
      endDate: 'Present',
      isCurrentRole: true,
      bulletPoints: [
        'Direct multiple simultaneous high-value infrastructure projects with capital budgets exceeding $15M.',
        'Coordinate cross-functional teams of engineers, architects, and sub-contractors to ensure strict adherence to quality and timeline milestones.',
        'Draft tender specifications, oversee contractor bidding, and negotiate contract terms with key vendors.',
        'Enforce rigorous site safety, environmental stewardship, and regulatory compliance protocols.',
      ],
    },
    {
      identifier: 'exp-en-2',
      jobTitle: 'Project Engineer & Cost Estimator',
      companyName: 'Apex Solutions Inc.',
      locationName: 'Montreal, QC',
      startDate: 'May 2021',
      endDate: 'Aug. 2022',
      isCurrentRole: false,
      bulletPoints: [
        'Formulated accurate preliminary and conceptual cost estimates for major commercial and residential development portfolios.',
        'Conducted detailed 2D/3D quantity take-offs using industry-standard engineering analysis platforms.',
        'Streamlined sub-contractor procurement pipelines, resulting in a 12% reduction in material acquisition overhead.',
      ],
    },
    {
      identifier: 'exp-en-3',
      jobTitle: 'Structural Engineering Analyst Intern',
      companyName: 'Horizon Capital Group',
      locationName: 'Montreal, QC',
      startDate: 'Jan. 2020',
      endDate: 'Apr. 2021',
      isCurrentRole: false,
      bulletPoints: [
        'Reviewed shop drawings and validated design calculations against relevant national and municipal building standards.',
        'Compiled structured monthly progress dashboards for executive stakeholders and client leadership.',
      ],
    },
  ],
  customSectionsList: [],
  sectionOrder: [
    'profile',
    'education',
    'projects',
    'experience',
    'skills',
    'languages',
    'certifications',
  ],
  sectionVisibility: {
    profile: true,
    education: true,
    projects: true,
    experience: true,
    skills: true,
    languages: true,
    certifications: true,
  },
};

